exports.usercontroller = require('./usercontroller')
exports.addresscontroller = require('./addresscontroller') 
exports.admincontroller = require('./admincontroller')
exports.productcontroller = require('./productcontroller')
exports.productStorecontroller = require('./productStorecontroller')
exports.ordercontroller = require('./ordercontroller')
